/* Generated by Yosys 0.69+ (git sha1 150c32b03, Release, GNU /usr/bin/g++-11 11.4.0) [github.com/ananthv26-cog-demo-repos/yosys-example at main] */

module counter8_en(clk, rst, en, count);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input en;
  wire en;
  output [7:0] count;
  wire [7:0] count;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  INVx1_ASAP7_75t_R _21_ (
    .A(rst),
    .Y(_08_)
  );
  AND3x1_ASAP7_75t_R _22_ (
    .A(en),
    .B(count[0]),
    .C(count[1]),
    .Y(_09_)
  );
  AND4x1_ASAP7_75t_R _23_ (
    .A(count[6]),
    .B(count[7]),
    .C(count[5]),
    .D(_13_),
    .Y(_15_)
  );
  AOI31xp33_ASAP7_75t_R _24_ (
    .A1(count[6]),
    .A2(count[5]),
    .A3(_13_),
    .B(count[7]),
    .Y(_16_)
  );
  NOR3xp33_ASAP7_75t_R _25_ (
    .A(rst),
    .B(_15_),
    .C(_16_),
    .Y(_06_)
  );
  AOI21xp33_ASAP7_75t_R _26_ (
    .A1(count[3]),
    .A2(_10_),
    .B(count[4]),
    .Y(_17_)
  );
  NOR3xp33_ASAP7_75t_R _27_ (
    .A(rst),
    .B(_13_),
    .C(_17_),
    .Y(_05_)
  );
  OAI21xp33_ASAP7_75t_R _28_ (
    .A1(en),
    .A2(count[0]),
    .B(_08_),
    .Y(_18_)
  );
  AOI21xp33_ASAP7_75t_R _29_ (
    .A1(en),
    .A2(count[0]),
    .B(_18_),
    .Y(_04_)
  );
  OAI21xp33_ASAP7_75t_R _30_ (
    .A1(count[5]),
    .A2(_13_),
    .B(_08_),
    .Y(_19_)
  );
  AOI21xp33_ASAP7_75t_R _31_ (
    .A1(count[5]),
    .A2(_13_),
    .B(_19_),
    .Y(_03_)
  );
  AOI21xp33_ASAP7_75t_R _32_ (
    .A1(en),
    .A2(count[0]),
    .B(count[1]),
    .Y(_20_)
  );
  AND4x1_ASAP7_75t_R _33_ (
    .A(en),
    .B(count[0]),
    .C(count[2]),
    .D(count[1]),
    .Y(_10_)
  );
  NOR3xp33_ASAP7_75t_R _34_ (
    .A(rst),
    .B(_09_),
    .C(_20_),
    .Y(_02_)
  );
  OAI21xp33_ASAP7_75t_R _35_ (
    .A1(count[3]),
    .A2(_10_),
    .B(_08_),
    .Y(_11_)
  );
  AOI21xp33_ASAP7_75t_R _36_ (
    .A1(count[3]),
    .A2(_10_),
    .B(_11_),
    .Y(_01_)
  );
  NOR2xp33_ASAP7_75t_R _37_ (
    .A(count[2]),
    .B(_09_),
    .Y(_12_)
  );
  NOR3xp33_ASAP7_75t_R _38_ (
    .A(rst),
    .B(_10_),
    .C(_12_),
    .Y(_00_)
  );
  AND3x1_ASAP7_75t_R _39_ (
    .A(count[3]),
    .B(count[4]),
    .C(_10_),
    .Y(_13_)
  );
  A2O1A1Ixp33_ASAP7_75t_R _40_ (
    .A1(count[5]),
    .A2(_13_),
    .B(count[6]),
    .C(_08_),
    .Y(_14_)
  );
  AOI31xp33_ASAP7_75t_R _41_ (
    .A1(count[6]),
    .A2(count[5]),
    .A3(_13_),
    .B(_14_),
    .Y(_07_)
  );
  DFFHQx4_ASAP7_75t_R _42_ (
    .CLK(clk),
    .D(_04_),
    .Q(count[0])
  );
  DFFHQx4_ASAP7_75t_R _43_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[1])
  );
  DFFHQx4_ASAP7_75t_R _44_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[2])
  );
  DFFHQx4_ASAP7_75t_R _45_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[3])
  );
  DFFHQx4_ASAP7_75t_R _46_ (
    .CLK(clk),
    .D(_05_),
    .Q(count[4])
  );
  DFFHQx4_ASAP7_75t_R _47_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[5])
  );
  DFFHQx4_ASAP7_75t_R _48_ (
    .CLK(clk),
    .D(_07_),
    .Q(count[6])
  );
  DFFHQx4_ASAP7_75t_R _49_ (
    .CLK(clk),
    .D(_06_),
    .Q(count[7])
  );
endmodule
